[project]
name = "hikcentral-openapi"
version = "0.1.1"
description = "Python library for HikCentral Open API"
authors = [{ name = "Rami Mousleh", email = "engrbm87@gmail.com" }]
requires-python = ">=3.11"
readme = "README.md"
dependencies = ["httpx>=0.28.1,<1.0.0", "pydantic>=2.12.3,<3.0.0"]

[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pre-commit>=4.1.0,<5", "pytest>=8.3.4,<9"]

[tool.uv]
default-groups = "all"

[tool.pylint.MAIN]
py-version = "3.11"
load-plugins = ["pylint.extensions.code_style", "pylint.extensions.typing"]

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "invalid-name",                 # N815
    "line-too-long",                # E501, disabled globally
    "too-many-arguments",
    "too-many-lines",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-branches",            # PLR0912
    "redefined-builtin",            # A001
    "protected-access",             # SLF001
]

[tool.pylint.FORMAT]
expected-line-ending-format = "LF"


[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = [".git", "testing_config"]
log_format = "%(asctime)s.%(msecs)03d %(levelname)-8s %(threadName)s %(name)s:%(filename)s:%(lineno)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
required-version = ">=0.8.0"

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = ["hikcentral_openapi"]
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.lint.mccabe]
max-complexity = 20
